const http = require('http');
const url = require('url')
const fs = require('fs');
const utils = require("./modules/utils")

class ServerManager {
    static #server
    static #portNum

    /** Creates the server and lists all the different endpoints of this server */
    constructor(portNum) {
        ServerManager.#portNum = portNum
        //create server generated by ChatGPT and modified
        ServerManager.#server = http.createServer((req, res) => {
            if (req.method === "GET") {
                if (req.url.includes("/getDate?")) {
                    ServerManager.#getDateAndName(req, res)
                }
                //else block generated by ChatGPT
                else {
                    res.writeHead(405, { 'Content-Type': 'text/plain' });
                    res.end('Invalid URL. Check your URL and make sure it is formatted properly.');
                }
            }
        })
        
        ServerManager.launchServer()
    }

    static launchServer() {
        ServerManager.#server.listen(ServerManager.#portNum, () => {
            console.log(`Server listening on port ${ServerManager.#portNum}`)
        })
    }

    static #getDateAndName(req, res) {
        const parsedUrl = url.parse(req.url, true); // `true` makes it parse query params into an object
        const queryParams = parsedUrl.query; // extract the query params and stores them into an object 

        const nameAndDate = utils.NameAndDatetime.getNameAndDate(queryParams.name)

        res.writeHead(200, {"content-type" : "text/html"})
        res.end(`<p style='color:blue;'>${nameAndDate}</p>`)
    }

}

let myServer = new ServerManager(8000);