//class idea generated by chat gpt
//handles storage and retrieval of data from local storage and timing
class LocalStorageManager {
    
    /** stores note objects that look like {note : "abc123"} */
    static #noteObjArr = []

    //will handle adding and removing notes from local storage
    updateLocalStorage() {
        localStorage.setItem("allNotes", JSON.stringify(LocalStorageManager.#noteObjArr))
        this.updateTime()
    }

    addNote(noteObj) {
        LocalStorageManager.#noteObjArr.push(noteObj)
        this.updateLocalStorage()
    }

    updateNote(noteDataObj, index) {
        LocalStorageManager.#noteObjArr.splice(index, 1, noteDataObj)
        this.updateLocalStorage()
    }

    deleteNote(index) {
        LocalStorageManager.#noteObjArr.splice(index, 1)
        this.updateLocalStorage()
    }

    getFromLocalStorage() {
        let notes = localStorage.getItem("allNotes")
        if (!(notes === undefined || notes === null)) {
            LocalStorageManager.#noteObjArr = JSON.parse(notes)
            return LocalStorageManager.#noteObjArr
        }
        return []
    }
    
    updateTime() {
        document.getElementById("time").innerHTML = new Date().toLocaleTimeString()
        // document.getElementById("time").insertAdjacentText("beforeend", new Date().toLocaleTimeString())
    }
}
