//class idea generated by chatGPT 
class NotesManager {
    //manages what notes there are by using local storage
    //will store array of note objects and update them

    static #localStorageMngr = new LocalStorageManager()

    /** stores Note objects as defined in note.js */
    static #notesArray = []

    constructor() {
        this.loadNotes()
        document.getElementById("add").addEventListener("click", () => {
            this.createNote()
        })
    }

    loadNotes() {
        // localStorage.removeItem("allNotes")
        let notes = NotesManager.#localStorageMngr.getFromLocalStorage()
        //notes is now an array of objects
        console.log(notes.length)
        for (let i = 0; i < notes.length; i++) {
            let tempNote = new Note(notes[i])
            NotesManager.#notesArray.push(tempNote)
            this.addListenersToNote(tempNote)
            document.getElementById("notes").insertAdjacentElement("afterbegin", tempNote.getNoteDiv())
        }
    }

    createNote(noteObj = null) {
        NotesManager.#notesArray.push(new Note(noteObj, NotesManager.#notesArray.length))

        let index = NotesManager.#notesArray.length - 1
        let tempNote = NotesManager.#notesArray.at(index)

        this.addListenersToNote(tempNote)

        NotesManager.#localStorageMngr.addNote(noteObj !== null ? noteObj : {note : ""})

        document.getElementById("notes").insertAdjacentElement("afterbegin", tempNote.getNoteDiv())
        // this.loadEventListeners()
    }

    addListenersToNote(noteObj) {
        noteObj.getNoteDiv().querySelector(".removeBtn").addEventListener("click", () => {
            this.deleteNote(noteObj)
        })
        noteObj.getNoteDiv().querySelector(".noteBox").addEventListener("keydown", () => {
            this.updateNotes(noteObj)
        })
    }

    updateNotes(noteObj) {
        // NotesManager.#notesArray.at(index)
        //get the text of the input field, create object and pass that obj to localStorageManager
        NotesManager.#localStorageMngr.updateLocalStorage(NotesManager.#notesArray)
    }

    deleteNote(noteObj) {
        noteObj.removeNoteDiv()

        let index = NotesManager.#notesArray.indexOf(noteObj)

        NotesManager.#notesArray.splice(index, 1)

        NotesManager.#localStorageMngr.deleteNote(index)
    }
}



//structure of how it will be stored in local storage
//allNotes will be a string key
{
    allNotes: [
        { note: "" },
        { note: "" },
        { note: "" },
        { note: "" },
        { note: "" },
        { note: "" },
        { note: "" },
    ]
}