//class idea generated by chatGPT 
class Note {
    //will create a text box that gets the note stored in local 
    //storage and populates the text box with that note
    
    #key
    #textBox
    #removeBtn
    #noteDiv
    
    // constructor() {        
    //     this.#key = ""
    //     this.#textBox = document.createElement("input")
    //     this.#removeBtn = document.createElement("button")

    //     this.#removeBtn.addEventListener("click", () => {
    //         this.remove()
    //     })
    // }

    /** 
     * notesObj: object structoreed as {note : "abc123"}
     */
    constructor(notesObj = null, key) {
        this.#key = key
        
        this.#textBox = document.createElement("input")
        this.#textBox.classList.add("noteBox")

        this.#removeBtn = document.createElement("button")
        this.#removeBtn.innerHTML = "remove"
        this.#removeBtn.classList.add("removeBtn")

        this.#noteDiv = document.createElement("div")
        this.#noteDiv.classList.add("noteDiv")

        this.#noteDiv.insertAdjacentElement("beforeend", this.#textBox)
        this.#noteDiv.insertAdjacentElement("beforeend", this.#removeBtn)
        this.#noteDiv.insertAdjacentElement("beforeend", document.createElement("br"))

        if (notesObj !== null) {
            this.#textBox.value = notesObj.note
        }
    }

    removeNoteDiv() {
        this.#noteDiv.remove()
    }

    getNoteDiv() {
        return this.#noteDiv
    }

    getNote() {
        return this.#textBox
    }

    getKey() {
        return this.#key
    }

}
