if (typeof(Storage) === undefined) {
    document.getElementById("notes").innerHTML = localStoreNA
} else {
    const notesManager = new NotesManager()
}


// document.getElementById("add").addEventListener("click", () => {
//     //create new note
//     notesManager.createNote()
// })

// document.querySelectorAll(".removeBtn").forEach((currentElement, currentIndex, listObj) => {
//     currentElement.addEventListener("click", () => {
//         notesManager.deleteNote(currentIndex)
//     })
// })

// document.querySelectorAll(".noteBox").forEach((currentElement, currentIndex, listObj) => {
//     currentElement.addEventListener("keydown", () => {
//         notesManager.updateNotes()
//     })
// })

//create document.querySelector to get all the buttons

//generated by chat gpt and modified
// function updateLocalStorage() {
//     //update the local storage

//     setInterval(() => {
//         // updateTime()-
//         document.getElementById("time").innerHTML = new Date().toLocaleTimeString()
//     }, 2000)
// }
// updateLocalStorage()

//decide whether to store just msg onto local storage or all components to local storage